### ISSUE TITLE
dcr --explain / ERROR: The file "sites/all/modules/custom" does not exist.

### ISSUE THREAD

**Issue by Decipher** [alexdesignworks/dcr#14] opened 2016-07-28 06:38 UTC
When I run the `dcr --explain` command I get the resulting error:

```
ERROR: The file "sites/all/modules/custom" does not exist.
```

**Comment by Decipher** [comment] 2016-07-28 06:42
Looks like the `--explain` part is irrelevant, assuming that if `dcr` is run without a specific target it assumes that you want to run it in `sites/all/modules/custom`.

**Comment by alexdesignworks** [comment] 2016-07-28 07:11
@Decipher yes, this is by design. I agree that those targets are not the best options - open to suggestions.

But the functionality to run `dcr` without targets cannot be changed. I.e., if you run `dcr` without targets it will use settings in `.dcr.yml`.

Open to suggestions to make the whole workflow better.

**Comment by alexdesignworks** [comment] 2016-08-01 11:27
Closing until better workflow is proposed

**Closed by alexdesignworks** 2016-08-01 11:27 UTC
